config/routes.rb
Rails3FullcalendarDemo::Application.routes.draw do
  resources :events
  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :client
  belongs_to :user, :foreign_key => :employee_id
  scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}
  
  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => false,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.scoped  
    @events = @events.after(params['start']) if (params['start'])
    @events = @events.before(params['end']) if (params['end'])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.js  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
      format.js { render :json => @event.to_json }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event    = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
      format.json { render json: @clients.map(&:name) }   
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(events_url, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  # PUT /events/1.js
  def update
    @event = Event.find(params[:id])
    
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(events_url, :notice => 'Event was successfully updated.') }
        format.js { head :ok}
      else
        format.html { render :action => "edit" }
        format.js  { render :js => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit_form.html.erb
<% remote_form_for @event, :url => {:action => :update} , :before => "$('#updating_events').show();", :complete => "$('#updating_events').hide();" do |f| %>
<p>
  <%=f.label :title %>
  <br/>
  <%=f.text_field :title %>
</p>
<p>
  <%=f.label :description %>
  <br/>
  <%=f.text_area :description, :rows => 4, :cols => 30 %>
</p>
<p>
  <%=f.label :starttime, 'Start Time' %>
  <br/>
  <%=f.datetime_select :starttime %>
</p>
<p>
  <%=f.label :endtime, 'End Time' %>
  <br/>
  <%=f.datetime_select :endtime %>
</p>
<p>
  <%=f.label :all_day %>
  <%=f.check_box :all_day %>
</p>
<%if false%>
<%period = (@event.event_series)?@event.event_series.period : nil -%>
<p>
  <%=f.label :period, "Repeats" %>
  <%=f.select :period, Event::REPEATS,{:selected => period}, :onchange => "showPeriodAndFrequency(this.value);" %>
</p>
<%frequency = (@event.event_series)?@event.event_series.frequency : nil -%>
<p id = "frequency" style = "display:<%(period)? '' : 'none'%>;">
  <%=f.label :frequency, "Repeat every" %>
  <%=f.select :frequency, (1..30).to_a, {:selected => frequency} %> <span id = "period"></span>
</p>
<%end%>
<%=f.hidden_field :id, :value => @event.id%>
<%=f.hidden_field :commit_button, :value => ""%>
<p>
  <%if @event.event_series -%>
  <%=f.submit 'Update Only This Occurrence', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%=f.submit 'Update All Occurrence', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%=f.submit 'Update All Following Occurrence', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%else-%>
  <%=f.submit 'Update', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%end-%>
  
  <span id = "updating_events" style = "display:none;">Updating, Please wait...</span>
</p>
<%end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p>
  <%=link_to 'Create Event', new_event_path %>
</p>


<div>

<div id="calendar"></div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Starts at:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @event.ends_at %>
</p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3FullcalendarDemo</title>
   

   <%= stylesheet_link_tag    "fullcalendar", :media => "all" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery.rest" %>
  <%= javascript_include_tag "rails" %>
  <%= javascript_include_tag "application" %>

  <%= javascript_include_tag "jquery-ui-1.8.11.custom.min" %>
  <%= javascript_include_tag "fullcalendar" %>
  <%= javascript_include_tag "calendar" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>